### ISSUE TITLE
LaTeX in examples on the website are broken

### ISSUE THREAD

**Issue by michaelmior** [aau-daisy/solvedb#2]
Sorry if this isn't the appropriate place to report, but on the [project website](http://www.daisy.aau.dk/?page_id=1198) the examples involving LaTeX code are currently broken.

For example, the URL http://www.forkosh.com/mathtex.cgi?x_1+2x_2%5Cleq1 returns a 502 error.

Personally, I've found CodeCogs to be useful for such a purpose. The equivalent URL for the example above is: https://latex.codecogs.com/gif.download?x_1+2x_2%5Cleq1

Therefore, fixing the issue would hopefully be a matter of replacing `http://www.forkosh.com/mathtex.cgi` with `https://latex.codecogs.com/gif.download`.

**Comment by lawrizs** [comment]
Thanks for the pointer. It is now fixed. Sorry for the delay - we have seen this quite late ;-)

**Comment by michaelmior** [comment]
Thanks!
